management:
  cloudfoundry:
    enabled: false
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env,heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health
---
spring:
  profiles: dev
server:
  port: 8000
---
spring:
  profiles: test
server:
  port: 9000